---
- hosts: all
  become: true
  vars:
    doc_root: /var/www/html
  tasks:
    - name: Update yum
      yum: update_cache=yes

    - name: Install Apache
      yum: 
         name: 
            - httpd 
         state: latest

    - name: Create custom document root
      file: path={{ doc_root }} state=directory owner=apache group=apache

    - name: Set up HTML file
      copy: src=index.html dest={{ doc_root }}/index.html owner=apache group=apache mode=0644
      notify: restart httpd

        # - name: Set up Apache virtual host file
        #template: src=vhost.tpl dest=/etc/apache2/sites-available/000-default.conf
       #     notify: restart apach
       #
    handlers:
        - name: restart apache
          service: 
            name: httpd 
            state: restarted

        # - name: start httpd
        #service:
        #   name: httpd
        #   state: started


